### ISSUE TITLE
Ingest a Google sheet with traffic fatalities information

### ISSUE THREAD

**Issue by CharlotteJackson** [CharlotteJackson/DC_Crash_Bot#65] opened 2021-04-15 15:29 UTC
# What is the Task
Set up a pipeline to a Google sheet with up-to-date fatalities information

## Why do we want to do this
The official crashes dataset does not accurately reflect fatality counts

## How can I get started?
Identify the google sheet to use, or create one ourselves
 
## Definition of Done
When there's an automated pipeline into the crashes database

**Comment by banjtheman** [comment] 2021-04-17 22:23
duplicate of https://github.com/CharlotteJackson/DC_Crash_Bot/issues/61

**Comment by banjtheman** [comment] 2021-04-22 01:16
This google sheet has information that can attempt to scrape 
https://docs.google.com/spreadsheets/d/1uCDD5ox8t4WDNB377PomsS3PS_QInaoE4_lGmqtxb-M/edit#gid=0


Once data is collected need to figure out where to ingest into db

**Comment by banjtheman** [comment] 2021-04-23 01:56
Script can be run, data uploaded to s3 as well

**Comment by eichler4dc** [comment] 2021-04-23 02:14
Unfortunately I can't open this google sheet in tableau.  Error message:  The Google Sheets service reported an unrecognized error when processing this request. This file is too large to be exported.

[Here's the URL to the sheet that I can successfully open](https://docs.google.com/spreadsheets/d/1IAEwjnRUvcGfhbzk_2_5Uso2SdhLbhht_zSdyXXBS0I/edit?usp=sharing).  Is there any way to do a "diff" of the two to see what the issue is?  Perhaps the one you're exporting programmatically has extra rows or columns in it that mine doesn't have when exported from Postgres via pgAdmin csv export.

**Comment by banjtheman** [comment] 2021-04-23 02:30
@eichler4dc Try using this sheet https://docs.google.com/spreadsheets/d/1_xDChirhrewq58RAlbKa02RhLQRyJ447zIpqFSGDG7A/edit#gid=225503231

the one above is for a different issue

**Comment by eichler4dc** [comment] 2021-04-23 12:48
sorry, i'm an idiot.  submitted feedback on the wrong issue.

**Closed** 2021-06-02 14:34 UTC

**Comment by eichler4dc** [comment] 2021-07-27 00:42
hi.  i'm noticing this data in the Source Data schema hasn't been updated since 4/27/2021.  Is this data load not automated yet?  Or did something change to disrupt the data flow?

**Comment by banjtheman** [comment] 2021-07-27 01:14
> 
> 
> hi. i'm noticing this data in the Source Data schema hasn't been updated since 4/27/2021. Is this data load not automated yet? Or did something change to disrupt the data flow?

what data source are you referring to?  Can you provide a URL?

**Comment by eichler4dc** [comment] 2021-07-27 01:26
sorry, this is for the Families for Safe Streets data that comes from a google sheet and gets loaded into source_data.dc_fss table 

source of data is here:  https://docs.google.com/spreadsheets/d/1uCDD5ox8t4WDNB377PomsS3PS_QInaoE4_lGmqtxb-M/edit#gid=0

**Comment by banjtheman** [comment] 2021-07-27 01:41
The data was being uploaded to a private bucket, just added a script to upload the data to a public bucket as well

https://dc-crash-bot-public.s3.amazonaws.com/source-data/dc-fss/dc_fss.csv

**Comment by CharlotteJackson** [comment] 2021-07-27 21:45
i need to throw a bash script/cron job on the EC2 instance that pulls the
csv into the database every night! Doing that now. Also Banjo about to
shoot you the certificate and the URL to it.
